version: '3.2'

services:
  tex-slave:
    build: ./tex-slave
    image: docker-registry.i.mm12.xyz/tex-slave:1.0.0
  latexbot:
    build: ./latexbot
    image: docker-registry.i.mm12.xyz/latexbot:0.11.0
    volumes:
      - type: volume
        source: latexbot-data
        target: /latexbot-data
      - type: bind # Allows for code testing without rebuild
        source: ./latexbot/latexbot
        target: /usr/local/lib/python3.9/site-packages/latexbot
    secrets:
      - latexbot-calendar-credentials
      - latexbot-credentials
    ports:
      - "8080:80"
    environment: 
      - LATEXBOT_DEBUG=1
      - LATEXBOT_DATA_DIR=/latexbot-data
      - LATEXBOT_CREDENTIALS_JSON=/run/secrets/latexbot-credentials
      - LATEXBOT_CALENDAR_CREDENTIALS=/run/secrets/latexbot-calendar-credentials
      - LATEXBOT_ANALYTICS=1
      - LATEXBOT_SERVER_PORT=80
      - LATEXBOT_SERVER_AUTH_ADMIN=admin
      - LATEXBOT_SERVER_AUTH_READ=read
      - LATEXBOT_SERVER_AUTH_WRITE=write
      - LATEXBOT_GH_HOOK_SECRET=${LATEXBOT_GH_HOOK_SECRET}
      - LATEXBOT_TBA_KEY=${LATEXBOT_TBA_KEY}
      - LATEXBOT_MAINTAINER_ID=${LATEXBOT_MAINTAINER_ID}

volumes: 
  latexbot-data:

secrets:
  latexbot-credentials:
    file: latexbot_credentials.json
  latexbot-calendar-credentials:
    file: calendar_credentials.json
