version: '3.2'

services:
  tex-slave:
    build: ./tex-slave
    image: docker-registry.i.mm12.xyz/tex-slave:1.0.0
  latexbot:
    build: .
    image: docker-registry.i.mm12.xyz/latexbot:0.5.1
    volumes: 
      - type: volume
        source: latexbot-data
        target: /usr/src/latexbot/data
    environment: 
      - PYTHONHASHSEED=0
      - LATEXBOT_ORG=${LATEXBOT_ORG}
      - LATEXBOT_USER=${LATEXBOT_USER}
      - LATEXBOT_PASS=${LATEXBOT_PASS}
      - LATEXBOT_SILENT=${LATEXBOT_SILENT}

volumes: 
  latexbot-data:
