version: '3.2'

services:
  tex-slave:
    build: ./tex-slave
    image: docker-registry.i.mm12.xyz/tex-slave:1.0.0
  latexbot:
    build: ./latexbot
    image: docker-registry.i.mm12.xyz/latexbot:0.11.0
    volumes:
      - type: volume
        source: latexbot-data
        target: /latexbot-data
    secrets:
      - latexbot-calendar-credentials
      - latexbot-credentials
    environment:
      - LATEXBOT_DATA_DIR=/latexbot-data
      - LATEXBOT_CREDENTIALS_JSON=/run/secrets/latexbot-credentials
      - LATEXBOT_CALENDAR_CREDENTIALS=/run/secrets/latexbot-calendar-credentials
      - LATEXBOT_ANALYTICS=1
      - LATEXBOT_SERVER_PORT=80
volumes: 
  latexbot-data:

secrets:
  latexbot-credentials:
    external: true
  latexbot-calendar-credentials:
    external: true
