version: '3.2'

services:
  tex-slave:
    build: ./tex-slave
    image: docker-registry.i.mm12.xyz/tex-slave:1.0.0
  latexbot:
    build: ./latexbot
    image: docker-registry.i.mm12.xyz/latexbot:0.10.0
    volumes:
      - type: volume
        source: latexbot-data
        target: /latexbot-data
      - type: bind
        source: ./latexbot/latexbot
        target: /usr/local/lib/python3.9/site-packages/latexbot
    ports:
      - "80:80"
    environment: 
      - PYTHONHASHSEED=0
      - LATEXBOT_DATA_DIR=/latexbot-data
      - LATEXBOT_ORG=${LATEXBOT_ORG}
      - LATEXBOT_USER=${LATEXBOT_USER}
      - LATEXBOT_PASS=${LATEXBOT_PASS}
      - LATEXBOT_DEBUG=${LATEXBOT_DEBUG}
      - LATEXBOT_ANALYTICS=${LATEXBOT_ANALYTICS}
      - LATEXBOT_GH_HOOK_SECRET=${LATEXBOT_GH_HOOK_SECRET}
      - LATEXBOT_SERVER_PORT=${LATEXBOT_SERVER_PORT}
      - LATEXBOT_SERVER_AUTH_ADMIN=${LATEXBOT_SERVER_AUTH_ADMIN}
      - LATEXBOT_SERVER_AUTH_READ=${LATEXBOT_SERVER_AUTH_READ}
      - LATEXBOT_SERVER_AUTH_WRITE=${LATEXBOT_SERVER_AUTH_WRITE}
      - LATEXBOT_TBA_KEY=${LATEXBOT_TBA_KEY}
      - LATEXBOT_MAINTAINER_ID=${LATEXBOT_MAINTAINER_ID}
      - LATEXBOT_CALENDAR_CRED_FILE=${LATEXBOT_CALENDAR_CRED_FILE}
      - LATEXBOT_NFFU_HMAC=${LATEXBOT_NFFU_HMAC}

volumes: 
  latexbot-data:
