version: '3.2'

services:
  tex-slave:
    build: ./tex-slave
    image: docker-registry.i.mm12.xyz/tex-slave:1.0.0
  latexbot:
    build: .
    image: docker-registry.i.mm12.xyz/latexbot:0.8.1
    volumes: 
      - type: volume
        source: latexbot-data
        target: /usr/src/latexbot/data
    ports: 
      - "80:80"
    environment: 
      - PYTHONHASHSEED=0
      - LATEXBOT_ORG=${LATEXBOT_ORG}
      - LATEXBOT_USER=${LATEXBOT_USER}
      - LATEXBOT_PASS=${LATEXBOT_PASS}
      - LATEXBOT_DEBUG=${LATEXBOT_DEBUG}
      - LATEXBOT_ANALYTICS=${LATEXBOT_ANALYTICS}
      - LATEXBOT_GH_HOOK_SECRET=${LATEXBOT_GH_HOOK_SECRET}
      - LATEXBOT_SERVER_PORT=${LATEXBOT_SERVER_PORT}
      - LATEXBOT_SERVER_AUTH_ADMIN=${LATEXBOT_SERVER_AUTH_ADMIN}
      - LATEXBOT_SERVER_AUTH_READ=${LATEXBOT_SERVER_AUTH_READ}
      - LATEXBOT_SERVER_AUTH_WRITE=${LATEXBOT_SERVER_AUTH_WRITE}
      - LATEXBOT_TBA_KEY=${LATEXBOT_TBA_KEY}

volumes: 
  latexbot-data:
